INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(1, 0, 'Assets', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(2, 0, 'Liabilities and Owners Equity', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(3, 0, 'Incomes', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(4, 0, 'Expenses', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(5, 1, 'Fixed Assets', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(7, 1, 'Investments', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(8, 2, 'Capital Stock', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(10, 2, 'Loans (Liabilities)', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(12, 4, 'Purchases', 1);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(14, 4, 'Indirect Expenses', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(15, 3, 'Sales', 1);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(17, 4, 'Manufacturing & Trading Expenses', 1);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(18, 4, 'Administrative Expenses', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(19, 4, 'Selling & Distribution Expenses', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(20, 4, 'Financial Expenses', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(22, 1, 'Current Assets', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(23, 22, 'Trade Debts', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(24, 2, 'Current Liabilities', 0);
INSERT INTO `groups` (`id`, `parent_id`, `name`, `affects_gross`) VALUES(25, 24, 'Trade Creditors', 0);
INSERT INTO entry_types (id, label, name, description, base_type, numbering, prefix, suffix, zero_padding, bank_cash_ledger_restriction) VALUES (1, 'receipt', 'Receipt', 'Received in Bank account or Cash account', 1, 1, '', '', 0, 2);
INSERT INTO entry_types (id, label, name, description, base_type, numbering, prefix, suffix, zero_padding, bank_cash_ledger_restriction) VALUES (2, 'payment', 'Payment', 'Payment made from Bank account or Cash account', 1, 1, '', '', 0, 3);
INSERT INTO entry_types (id, label, name, description, base_type, numbering, prefix, suffix, zero_padding, bank_cash_ledger_restriction) VALUES (3, 'contra', 'Contra', 'Transfer between Bank account and Cash account', 1, 1, '', '', 0, 4);
INSERT INTO entry_types (id, label, name, description, base_type, numbering, prefix, suffix, zero_padding, bank_cash_ledger_restriction) VALUES (4, 'journal', 'Journal', 'Transfer between Non Bank account and Cash account', 1, 1, '', '', 0, 5);
